### PR TITLE
Wait for NIC and Search for built-in Administrator account fixes

### PR DESCRIPTION
**Pull request by kvaps**
Hi, this pull requset solve the problem: When the nic driver not yet installed, but the script already configures nic. Due this problem the IP configuration may be not configured.

Also includes @andremonteir fix for search for built-in Administrator account in system language.

### CODE REVIEW

**Comment by FlorianHeigl** [comment]
Hi,

this might be a stupid question, but what's the magic behind the SID here:

>  { $_.SID -like "S-1-5-32-544" }

is that some hardcoded magic in sysprep or how can it be fixed?

**Comment by kvaps** [comment]
Hi FlorianHeigl,

>SID: S-1-5-32-544
>Name: Administrators
>Description: A built-in group. After the initial installation of the operating system, the only member of the group is the Administrator account. When a computer joins a domain, the Domain Admins group is added to the Administrators group. When a server becomes a domain controller, the Enterprise Admins group also is added to the Administrators group.

from: https://support.microsoft.com/en-us/kb/243330

**Comment by jfontan** [comment]
Thanks!

**Comment by twangboy** [comment]
This causes the script to hang if a second NIC is defined (ETH1) and there is only 1 NIC on the system.

**Comment by FlorianHeigl** [comment]
@kvaps can you please check that?

(I don't fully understand right now - how can a second nic be defined (as per the template I guess) but only one be on the system?)

**Comment by kvaps** [comment]
Hi All!
As I understand,  this bug can be found only in one situation:
When you create vm from template with two nics, then remove first nic from vm.

Also I know that this script was originally written only for first vm run, and this limitation was dirty turned off in f9ff746

I don't see anything wrong in this, that script would be execute every time when vm start, but something needs to be changed.
In my look [while](https://github.com/OpenNebula/addon-context-windows/blob/master/context.ps1#L81) loop and [increment](https://github.com/OpenNebula/addon-context-windows/blob/master/context.ps1#L150-L152) variables need be replaced something like this in [addon-context-linux](https://github.com/OpenNebula/addon-context-linux/blob/80951d036f8db787d9c50585856dd852226590dd/base_arch/etc/one-context.d/10-network#L176):
```bash
env | grep -E "^ETH[0-9]+_MAC=" | sed 's/_.*$//' | sort
```

Also you may to use dirty workaround, by adding timeout for the nic lookup.

**Pull request merged**
